### ISSUE TITLE
IndexError: bytearray index out of range

### ISSUE THREAD

**Issue by Chiggy-Playz** [xxxzsx/pyripper#1]
Command I used : `unpyarmor unpack enc.bin pytransform.key out.pyc`
Output:
```
You are using python (3, 7), but this script was packed with (48, 48), expect errors!
Traceback (most recent call last):
  File "/home/chiggy/.local/bin/unpyarmor", line 11, in <module>
    load_entry_point('unpyarmor', 'console_scripts', 'unpyarmor')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/Chiggy/Desktop/unpyarmor-master/unpyarmor/main.py", line 34, in unpack
    dec = do_unpack(enc, key)
  File "/mnt/c/Users/Chiggy/Desktop/unpyarmor-master/unpyarmor/main.py", line 16, in do_unpack
    co = restore_codeobj(armor.code, pubkey)
  File "/mnt/c/Users/Chiggy/Desktop/unpyarmor-master/unpyarmor/unpack.py", line 33, in restore_codeobj
    deccode = decode_buffer(deccode)
  File "/mnt/c/Users/Chiggy/Desktop/unpyarmor-master/unpyarmor/crypto.py", line 23, in decode_buffer
    inp[0] = (~inp[0]) & 0xff
IndexError: bytearray index out of range
```

**Comment by xxxzsx** [comment]
Then leave this issue in unpyarmor repo.

**Comment by Chiggy-Playz** [comment]
Sorry I pasted the wrong command. I used `pyripper rip enc.bin pytransform.key out.pyc` and it gave same error. Then I tried unpackarmor and still same error. Sorry mixed up the commands. Do you want me to paste the enc.bin file?

**Comment by xxxzsx** [comment]
Will be solved soon.

**Comment by Chiggy-Playz** [comment]
@xxxzsx any eta?
